/*
 * ShapePreviewPanelAdvanced.java
 *
 * Created on 02.12.2011, 20:40:32
 */
package stargate;

import classes.Cube3D;
import classes.vector.Vector3D;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author RRD
 */
public class ShapePreviewPanelAdvanced extends javax.swing.JPanel {
    
    private double size = 50.0;
    
    private Vector3D xAxis = new Vector3D(1.0, 0.0, 0.0);
    private Vector3D yAxis = new Vector3D(0.0, 1.0, 0.0);
    private Vector3D zAxis = new Vector3D(0.0, 0.0, 1.0);
    
        
    /** Creates new form ShapePreviewPanelAdvanced */
    public ShapePreviewPanelAdvanced() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        draw3DCube((Graphics2D) g);
    }
    
    protected void draw3DCube(Graphics2D graphics) {
        
        Vector3D startPoint = new Vector3D(getWidth() / 2.0, getHeight() / 2.0, getHeight() / 2.0);
        
        Cube3D testCube = new Cube3D(startPoint, size);
        
        testCube.draw(graphics, xAxis, yAxis, zAxis);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
